# on:
#   schedule:
#   - cront: '*/5 * * * *'

on: [push]

jobs:
  slack_notify:
    runs-on: ubuntu-latest
    name: A job to send a message to slack
    steps:
    - name: Slack notification
      id: slack
      uses: kiyo27/action-slack-notify@main
      env:
        TOKEN: ${{ secrets.TOKEN }}
        WEBHOOK: ${{ secrets.WEBHOOK }}
