name: parameter
# on: create
jobs:
  parameter:
    name: My Checkout Job
    runs-on: ubuntu-latest
    steps:
      - name: Set parameter
        id: random-number-generator
        run: echo "::set-output name=random-number::$(echo $RANDOM)"
        shell: bash
      - name: Result env
        run: >
          echo output parameter is ${{ steps.random-number-generator.outputs.random-number }}